IF EXISTS (SELECT C.NAME FROM SYS.COLUMNS C WHERE C.OBJECT_ID = OBJECT_ID('EVA_SAE_TramiteSolicitud'))
BEGIN
	IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'EVA_SAE_TramiteSolicitud' AND COLUMN_NAME = 'SLA')
	BEGIN
		ALTER TABLE EVA_SAE_TramiteSolicitud
		Add SLA INT Null
	END
END