IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE TABLE_NAME = 'EVA_SAE_TramiteRequisito' AND CONSTRAINT_NAME = 'UNQ_TramiteRequisito')
BEGIN
	ALTER TABLE EVA_SAE_TramiteRequisito
	DROP CONSTRAINT UNQ_TramiteRequisito
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE TABLE_NAME = 'EVA_SAE_TramiteRequisito' AND CONSTRAINT_NAME = 'FK_TramiteRequisito_TramiteCaso_IdCaso')
BEGIN
	ALTER TABLE EVA_SAE_TramiteRequisito
	ADD CONSTRAINT FK_TramiteRequisito_TramiteCaso_IdCaso FOREIGN KEY (IdCaso) REFERENCES EVA_SAE_TramiteCaso (IdCaso)
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE TABLE_NAME = 'EVA_SAE_TramiteRequisito' AND CONSTRAINT_NAME = 'UQ_IdTramite_IdCaso_IdRequisito')
BEGIN
	ALTER TABLE EVA_SAE_TramiteRequisito
	ADD CONSTRAINT UQ_IdTramite_IdCaso_IdRequisito UNIQUE (IdTramite, IdCaso, IdRequisito)
END